[features]
seeds = false
[programs.devnet]
gifportal = "G17S2GuHnJS9x63biCJZk48smtPfthsKcatfxcE1zL1u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/goti/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
